services:
  - type: web
    name: artales-backend
    env: node
    plan: free
    runtime: node
    buildCommand: "npm ci"
    startCommand: "bash render-start.sh"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
